class AgentStatus:
    SUCCESS = "SUCCESS"
    POLICY_REJECT = "POLICY_REJECT"
    MARKET_FREEZE = "MARKET_FREEZE"
    PROCESS_SLOW = "PROCESS_SLOW"
    DATA_ERROR = "DATA_ERROR"
    UNAVAILABLE = "UNAVAILABLE"
